{"name": "test_2_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3", "trace": "self = <test_2_storm.TestDemo2 object at 0x000001D7FA16EB60>\n\n    @allure.story(\"测试用例2-1\")\n    @allure.severity(\"minor\")\n    def test_2_1(self):\n        \"\"\"\n        用例描述：这是一个用例的描述\n        :return:\n        \"\"\"\n        a = 1 + 1\n>       assert a == 3\nE       assert 2 == 3\n\ntest_2_storm.py:24: AssertionError"}, "description": "\n        用例描述：这是一个用例的描述\n        :return:\n        ", "start": 1680961467727, "stop": 1680961467727, "uuid": "c1addbef-a5a6-4d8b-9da3-de6da2813d57", "historyId": "82c83fd743688587909749e73866734e", "testCaseId": "626b535ef0d168f864af3f7c452bf26a", "fullName": "test_2_storm.TestDemo2#test_2_1", "labels": [{"name": "story", "value": "测试用例2-1"}, {"name": "severity", "value": "minor"}, {"name": "suite", "value": "test_2_storm"}, {"name": "subSuite", "value": "TestDemo2"}, {"name": "host", "value": "hy-PC"}, {"name": "thread", "value": "10548-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_2_storm"}]}